### ISSUE TITLE
執行時遇到問題

### ISSUE THREAD

**Issue by sy-ctll** [RetCute/GalTranslator#2]
執行時報urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1122)
能請問下怎麽解決嗎，謝謝！

**Comment by RetCute** [comment]
留下详细错误以及错误代码行 便于分析解答

**Comment by sy-ctll** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "D:\360MoveData\Users\Hasee\Desktop\GalTranslator-main\main.py", line 196, in monitor
    translator.ask("请将这段日文符合语气地优美地贴合原意地翻译为中文只给出翻译后的结果即可无需添加其他东西" + text)
  File "D:\360MoveData\Users\Hasee\Desktop\GalTranslator-main\main.py", line 44, in ask
    txtbox.send_keys(text)
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=121.0.6167.161)
Stacktrace:
	GetHandleVerifier [0x00C81673+52979]
	(No symbol) [0x00C07961]
	(No symbol) [0x00AEDC00]
	(No symbol) [0x00B221D8]
	(No symbol) [0x00B21299]
	(No symbol) [0x00B444EC]
	(No symbol) [0x00B1DA4E]
	(No symbol) [0x00B44784]
	(No symbol) [0x00B5B3FE]
	(No symbol) [0x00B44286]
	(No symbol) [0x00B1C063]
	(No symbol) [0x00B1CECD]
	GetHandleVerifier [0x00F98D83+3294723]
	GetHandleVerifier [0x00FD6CC2+3548482]
	GetHandleVerifier [0x00FD1C9C+3527964]
	GetHandleVerifier [0x00D1870E+671630]
	(No symbol) [0x00C11EB4]
	(No symbol) [0x00C0D808]
	(No symbol) [0x00C0D92D]
	(No symbol) [0x00BFF7E0]
	BaseThreadInitThunk [0x77317BA9+25]
	RtlInitializeExceptionChain [0x77C1BD2B+107]
	RtlClearBits [0x77C1BCAF+191]
就是在按下熱鍵后報的錯，網頁上會跳轉到chatgpt4的購買畫面

**Comment by RetCute** [comment]
试试你是否可以正常使用ChatGPT 或者可能是GPTPlus过期了切换到3.5t试试

**Comment by RetCute** [comment]
问题已经解决 为偶发性事件 讲translator ask中的寻找元素替换为By.ID和prompt-textarea 然后删去click 稍后会更新源文件
